# Generated by Django 4.1.6 on 2023-02-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catg_tipo_producto',
            fields=[
                ('pk_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'catg_tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('pk_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=35)),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('fk_tipo_producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.catg_tipo_producto')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
